### ISSUE TITLE
deprecate FormGroup component

### ISSUE THREAD

**Issue by jrios** [TWExchangeSolutions/es-components#11]
I don't think this really adds much value. I think we should just remove this all together. Thoughts?

**Comment by Darrken** [comment]
Yeah if all it's doing is adding spacing, a component seems like overkill.

**Comment by aabenoja** [comment]
While I am not a fan of `FormGroup` we do have a very similar component downstream. Knowing this we could keep it so that there is some parity with the design updates across consumers, but I think it's perfectly acceptable to handle this on a per-project basis than host this upstream.

**Comment by jrios** [comment]
addressed in #14

**Comment by Darrken** [comment]
Are we keeping this then, or removing it?

**Comment by jrios** [comment]
I have another PR coming up that will address this. had to address a few other needs that will result in a v 2.0

**Comment by Darrken** [comment]
Cool. Looks like we're set to remove the style folder too.

**Comment by jrios** [comment]
Nice. I'll pull that out as well. 👍

**Comment by jrios** [comment]
Now addressed in #16
