### ISSUE TITLE
Popover: use dashed underline on link

### ISSUE THREAD

**Issue by Darrken** [TWExchangeSolutions/es-components#30]
Replace the solid underline in the popover sample to a dashed underline.

**Comment by jrios** [comment]
This shouldn't be on just the sample, we want all PopoverLink components to have the dashed underline.

**Comment by Darrken** [comment]
Ah yeah, I was thinking of the tooltip.  The popover has the popoverLink which can be styled.

**Comment by jrios** [comment]
I can take on these popover changes since I'll be in that area soon.

**Comment by Darrken** [comment]
Cool. While you're in there I noticed we can get rid of the extra surrounding span tag in PopoverLink by moving the Overlay element into the one that holds the Button.
