### ISSUE TITLE
upgrade to styled-components v2

### ISSUE THREAD

**Issue by jrios** [TWExchangeSolutions/es-components#41]
Some nice upgrades in the next version. Should be a pretty simple update even if we don't use the additional features immediately.

https://medium.com/styled-components/announcing-v2-f01ef3766ac2

**Comment by Darrken** [comment]
Wow, yeah there are some cool additions.  The server-side rendering sounds impressive.

**Comment by jrios** [comment]
It also looks like they're trying to get CSS extraction as well, which could be helpful. fingers crossed on that one.
