### ISSUE TITLE
Updated react-animate-height causing CI failures

### ISSUE THREAD

**Issue by aabenoja** [TWExchangeSolutions/es-components#74]
The three failing tests are all because of a recent update to the `react-animate-height` library. However, these fail only because the element is getting mounted in jsDOM and the DOM element ref does not have the `style` object on it. This should not affect any deployments. Not entirely sure yet if we should lock down to `0.9.9` like I already have with the node v8 test run or to continue floating it. Thoughts? @Darrken @jrios

**Comment by Darrken** [comment]
Just lock it at 0.9.9 for now is my vote. It doesn't sound like he's going to have time to address it soon based on his response to your issue. We can check in on it later.

**Comment by aabenoja** [comment]
Closed by #75
